name: Deploy

on:
  workflow_run:
    workflows: ["Go Code Check"]
    types: [ completed ]
  workflow_dispatch:
  deployment:
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - run: git branch

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: "nicolasparada"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nicolasparada/nakama:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Secure copy docker-compose.yaml
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yaml"
          target: "."

      - name: SSH & docker-compose up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo >| .env \
            && echo "${{ secrets.SENDGRID_API_KEY }}" > .env \
            && echo "${{ secrets.TRAEFIK_PILOT_TOKEN }}" > .env \
            && docker-compose pull \
            && docker-compose up -d --force-recreate
